name: Generate pacman animation

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: rohit0828

      - name: Debug - List files
        run: ls -R

      - name: Copy SVG to dist/
        run: |
          mkdir -p dist
          cp pacman-contribution-graph*.svg dist/


      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit to main branch to count as contribution
        run: |
          echo "Update timestamp: $(date)" > timestamp.txt
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add timestamp.txt
          git commit -m "Update timestamp to trigger green square" || echo "No changes to commit"
          git push origin main
